### ISSUE TITLE
multiple resource scripts > failed connection

### ISSUE THREAD

**Issue by rnieuweveen** [Tools4everBV/HelloID-Conn-Prov-Target-ExchangeOn-Premise#2]
When using multiple resource scripts the same session will be used and results in an error while creating one of the resources.

https://github.com/Tools4everBV/HelloID-Conn-Prov-Target-ExchangeOn-Premise/blob/ad925009666777e3e09245a70a898c668c134b3e/resources.groups.ps1#L91C2-L91C3

**Comment by jbreek** [comment]
Couldn't reproduce this. Looks like resource scripts are handled sequentially. Ran enforcement with creating resources for sharedmailboxes and distributiongroups in sessions with the same name without issues.
